version: '2'
services:
  server-app:
    image: server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://server-postgresql:5432/server
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://server-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://server-elasticsearch:9200
    ports:
      - 8080:8080
  server-postgresql:
    extends:
      file: postgresql.yml
      service: server-postgresql
  server-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: server-elasticsearch
